################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.c \
../CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.o \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_partial_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_conv_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_correlate_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_fast_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_init_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_norm_q31.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q15.d \
./CMSIS/DSP_Lib/Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
CMSIS/DSP_Lib/Source/FilteringFunctions/%.o: ../CMSIS/DSP_Lib/Source/FilteringFunctions/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU C Compiler'
	arm-none-eabi-gcc -mthumb -mcpu=cortex-m3 -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\CMSIS -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\CMSIS\startup_gcc -I"P:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\CMSIS\Include" -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_gpio -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_hpdma -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_i2c -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_nvm -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_spi -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_sys_services -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_timer -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers\mss_uart -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers_config -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\drivers_config\sys_config -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\hal -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\hal\CortexM3 -IP:\fred\OMNI\Libero\Mario-CM_Flex-EMG_golden_STAPL\Mario_SF2_m2s025\SoftConsole\Mario_Libero_MSS_CM3\Mario_Libero_MSS_CM3_hw_platform\hal\CortexM3\GNU -O0 -ffunction-sections -fdata-sections -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -o"$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


